- hosts: calipers
  gather_facts: false
  roles:
    - role: caliper
      vars:
        caliper_actions:
          - configure:
              - hostfile
              - chaincode
              - networks-config
              - caliper-config
        caliper_workspace: /opt/hyperledger/caliper
        caliper_config_sut_version: 2.1.0