- name: Check if msp exists
  stat:
    path: "{{ playbook_dir }}/{{ bld_msp_config_name }}/crypto-config"
  register: msp_exists

- name: Error - no msp
  fail:
    msg: crypto-config is not exists
  when: not msp_exists.stat.exists

- name: set configtx.yaml
  template:
    src: configtx.yaml.jinja
    dest: "{{ playbook_dir }}/{{ bld_msp_config_name }}/configtx.yaml"

- name: generate channel creation tx
  shell: bin/configtxgen -profile SampleProfile -outputCreateChannelTx mychannel.tx -channelID mychannel
  args:
    chdir: "{{ playbook_dir }}/{{ bld_msp_config_name }}"

- name: include generate anchor peer update tx
  include_tasks: "inner-anchor-update.yml"
  with_items:
    - "{{ bld_peer_orgs }}"
  loop_control:
    loop_var: org
