- name: Install docker
  become: true
  block:
    - name: install yum-utils
      yum:
        name:
          - yum-utils
        state: present
    - name: setup repository
      shell: yum-config-manager \
              --add-repo \
              https://download.docker.com/linux/centos/docker-ce.repo
    - name: install docker
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
    - name: Start docker service
      become: true
      systemd:
        name: "docker"
        enabled: yes
        state: started
