- name: run install-{{ chaincode_name }}.sh
  command: bash -ic './install-{{ chaincode_name }}.sh'
  args:
    chdir: "{{ caliper_workspace | mandatory }}"
  register: ps
- name: print result
  debug:
    var: ps.stdout