- name: Check Dist Version
  shell:
    cmd: source /etc/os-release && echo $ID
  args:
    executable: /bin/bash

  register: os_distribution

- name: check docker installed
  become: true
  shell: "which docker"
  register: docker_exists
  ignore_errors: true

- name: include package install task
  include_tasks: "install-docker/{{ os_distribution.stdout }}.yml"
  when: docker_exists.rc != 0