- name: Check Dist Version
  shell:
    cmd: source /etc/os-release && echo $ID
  args:
    executable: /bin/bash

  register: os_distribution

- name: include mqtt install task
  include_tasks: "mqtt-{{ os_distribution.stdout }}.yml"

